config/routes.rb
Rails.application.routes.draw do

  get 'sitemap', :to => 'sitemap#index'

  get 'topics/:id', to: 'topics#show', as: 'topic'

  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'sessions/index' #for SSO redirect

  root 'landing#index'
end

app/models/discourse_api_parser.rb
class DiscourseApiParser
  def initialize(response_hash)
    @response_hash = response_hash
  end

  def topics
    topic_parsers = []
    @response_hash.fetch('topics', []).each do |t|
      topic_parsers << DiscourseTopicParser.new(t)
    end
    topic_parsers
  end
end

app/models/discourse_topic_parser.rb
class DiscourseTopicParser
  def initialize(topic_hash)
    @topic_hash = topic_hash
  end

  def title
    @topic_hash.fetch('title')
  end

  def image_url
    url = @topic_hash.fetch('image_url')
    return url if url.start_with?('http')
    "#{Settings.discourse.host}/#{url}"
  end

  def pointer_tags
    tags = []
    @topic_hash.fetch('excerpt', '').split(',').each do |token|
      tags << token.strip[1 .. -1]
    end
    tags
  end

  def id
    @topic_hash.fetch('id')
  end
end

app/models/registered_user.rb
class RegisteredUser
  attr_reader :id, :username
  def initialize(opts)
    @id = opts.fetch('id')
    @username = opts.fetch('username')
  end
end

app/models/topic.rb
class Topic
  attr_accessor :title, :body
end

app/models/topic_builder.rb
class TopicBuilder
  def initialize(topic_hash)
    @topic_hash = topic_hash
  end

  def build
    topic = Topic.new
    topic.title = topic_title
    topic.body = topic_body
    topic
  end
  private
  def topic_title
    @topic_hash['title']
  end

  def topic_body
    @topic_hash.dig('post_stream', 'posts').at(0).fetch('cooked')
  end
end

app/models/topic_list.rb
class TopicList
  attr_reader :items
  def initialize(topic_list_items)
    @items = topic_list_items
  end
end

app/models/topic_list_builder.rb
class TopicListBuilder
  class << self
    def build_topic_list(topic_list_hash)
      topics = topic_list_hash.dig('topic_list', 'topics').select{|x| x['excerpt'].present?}
      items = topics.map {|t| build_topic_list_item(t) }
      TopicList.new(items)
    end

    private
    def build_topic_list_item(topic_list_item_hash)
      TopicListItemBuilder.new(topic_list_item_hash).build
    end
  end
end

app/models/topic_list_item.rb
class TopicListItem
  attr_accessor :title, :excerpt, :id, :created_at, :thumbnail
end

app/models/topic_list_item_builder.rb
class TopicListItemBuilder
  def initialize(topic_list_item_hash)
    @item_hash = topic_list_item_hash
  end

  def build
    item            = TopicListItem.new
    item.title      = title
    item.excerpt    = excerpt
    item.id         = id
    item.created_at = created_at
    item.thumbnail  = thumbnail
    item
  end

  private
  def title
    @item_hash['title']
  end

  def excerpt
    @item_hash['excerpt']
  end

  def id
    @item_hash['id']
  end

  def created_at
    DateTime.parse(@item_hash['created_at'])
  end

  def thumbnail
    path = @item_hash.dig('thumbnails','normal') || "https://www.google.com/logos/doodles/2016/lotte-reinigers-117th-birthday-5079873255112704.2-res.png"
    return path if path.starts_with?('http')
    "#{Settings.discourse.host}/#{relative_path}"
  end
end

app/models/unregistered_user.rb
class UnregisteredUser
  def username
    'Visitor'
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @topic_list = TopicListService.get_topics_by_category(discourse_category)
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
    @topic_list = TopicListService.get_topics_by_category(discourse_category)
    respond_to do |format|
      format.xml { render :layout => false }
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = TopicService.find_topic_by_id(topic_id)
  end
  
  private
  def topic_id
    params.permit(:id).require(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogger_posts_helper.rb
module BloggerPostsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/views/elements/_footer.html.erb
<%= tag :hr %>
<footer class="footer">
  <h1> footer </h1>
</footer>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">
        <img alt="Brand" height="22" src="https://www.google.com/logos/doodles/2016/lotte-reinigers-117th-birthday-5079873255112704.2-res.png">
      </a>
    </div>
      <%= render partial: 'elements/session_panel' %>
  </div>
</nav>

app/views/elements/_session_panel.html.erb
<div>
  <span>Hello, <%= current_user.username %></span>
  <% if user_logged_in? %>
    <%= link_to 'Log out', :controller => :sessions, :action => :destroy %>
  <% else %>
    <%= link_to 'Log In', :controller => :sessions, :action => :new %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>frontier</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
</head>
<body>
  <div class="container">
    <%= render partial: "elements/navbar" %>
    <%= yield %>
    <%# render partial: "elements/footer" %>
  </div>
</body>
</html>

app/views/partials/_topic_list_item.html.erb
<h2> <%= topic_list_item.title %> </h2>
<%= link_to "Enter", topic_path(topic_list_item.id)%>
<%= image_tag topic_list_item.thumbnail, size: '100' %>
<p> <%= raw topic_list_item.excerpt %> </p>